FROM node:alpine

ADD package_d2m.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /opt/app && cp -a /tmp/node_modules /tmp/package.json /opt/app/
RUN mkdir /opt/app/data
WORKDIR /opt/app
ADD dat2mongo.js /opt/app/
ADD crontab.tmp /opt/app
ADD runscript.sh /opt/app
RUN mkdir /var/log/d2m

RUN crontab crontab.tmp

RUN touch cmds.sh \
	&& echo 'crond && ./runscript.sh' >cmds.sh

CMD sh ./cmds.sh

