FROM node:9-alpine

ADD package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /opt/app && cp -a /tmp/node_modules /opt/app/
RUN mkdir /opt/app/data 

WORKDIR /opt/app
ADD dat2mongo.js location.js readFromcvs.js package.json jquery.csv.js /opt/app/
ADD dat2mongo_new.js /opt/app
# ADD readFromcvs2Shard.js /opt/app
ADD data/mysids.txt /opt/app/data
ADD crontab.tmp /opt/app

RUN crontab crontab.tmp

RUN touch cmds.sh \
	&& echo 'crond -f' >cmds.sh

CMD sh ./cmds.sh

