FROM node:9-alpine

ADD package_d2m.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /opt/app && cp -a /tmp/node_modules /tmp/package.json /opt/app/
RUN mkdir /opt/app/data
WORKDIR /opt/app
ADD dat2mongo.js /opt/app/
ADD data/mysids.txt /opt/app/data
ADD crontab.tmp /opt/app

RUN crontab crontab.tmp

RUN touch cmds.sh \
	&& echo 'crond -f' >cmds.sh

CMD sh ./cmds.sh

